### ISSUE TITLE
Possible bug in codespace for class set-up; won't allow selection of Python Environments...

### ISSUE THREAD

**Issue by cbush2014** [LinkedInLearning/data_cleaning_python_2883183#1]
## Issue Overview

Possible bug in codespace for class set-up; won't allow selection of Python Environments...
## Describe your environment

open codespace in Firefox or Chrome
## Steps to Reproduce

1. open codespace in Firefox or Chrome
2. open Ch01/01_02/missing.py and prompted to install recommended Jupyter extension.
3. click on Run Cell for first code block in missing.py; opens Interactive-1 window in vscode with "Select a kernel to run cells."
4. This pops up "Select Kernel" window (type to choose a kernel source), and the only option is 
"Existing Jupyter Server..."

## Expected Behavior

In the same situation on my windows 10 desktop version of vscode, I have 2 options when I need to select a kernel:    
Python Environments...
Existing Jupyter Server...

## Current Behavior

only provided one option for kernel selection: Existing Jupyter Server...
## Related Issues

If you are updating the codespace, maybe you can add the installation of "Invoke" so users won't have to  do a "pip install invoke" to be able to run the etl's in the course

I noticed that someone in another class has the same problem with their codespace: https://lnkd.in/geMxYZBi

**Comment by ashrobertsdragon** [comment]
I am having this issue as well

**Comment by tebeka** [comment]
Codespaces was not setup for this class, it starts with default environment that is missing some installations.
We're discussing internally how to proceed.

**Comment by tebeka** [comment]
After some investigation. There were two issues:
- The right repo for the course is https://github.com/LinkedInLearning/data-cleaning-in-python-essential-training-3086536 and not this one
- Codespaces now work on the right repo.

Thanks and sorry for the confusion.
